// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'domain/entities/news_item.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 1836617437630631139),
      name: 'NewsItem',
      lastPropertyId: const obx_int.IdUid(10, 5908834045285893994),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6830948957545032414),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6434084184899770605),
            name: 'remoteId',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(1, 4527441301033068830)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5322531431066773890),
            name: 'title',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(2, 9039780979785919012)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1951414928004210979),
            name: 'content',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 7047281909352551603),
            name: 'summary',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 5820651682019078899),
            name: 'imageUrl',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 1064367844623641455),
            name: 'sourceName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 6061287600725833536),
            name: 'publishDate',
            type: 10,
            flags: 8,
            indexId: const obx_int.IdUid(3, 801685968950944828)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 7286980942533170532),
            name: 'isRead',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 5908834045285893994),
            name: 'isPriority',
            type: 1,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 1836617437630631139),
      lastIndexId: const obx_int.IdUid(3, 801685968950944828),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    NewsItem: obx_int.EntityDefinition<NewsItem>(
        model: _entities[0],
        toOneRelations: (NewsItem object) => [],
        toManyRelations: (NewsItem object) => {},
        getId: (NewsItem object) => object.id,
        setId: (NewsItem object, int id) {
          object.id = id;
        },
        objectToFB: (NewsItem object, fb.Builder fbb) {
          final remoteIdOffset = fbb.writeString(object.remoteId);
          final titleOffset = fbb.writeString(object.title);
          final contentOffset = fbb.writeString(object.content);
          final summaryOffset = fbb.writeString(object.summary);
          final imageUrlOffset = object.imageUrl == null
              ? null
              : fbb.writeString(object.imageUrl!);
          final sourceNameOffset = fbb.writeString(object.sourceName);
          fbb.startTable(11);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, remoteIdOffset);
          fbb.addOffset(2, titleOffset);
          fbb.addOffset(3, contentOffset);
          fbb.addOffset(4, summaryOffset);
          fbb.addOffset(5, imageUrlOffset);
          fbb.addOffset(6, sourceNameOffset);
          fbb.addInt64(7, object.publishDate.millisecondsSinceEpoch);
          fbb.addBool(8, object.isRead);
          fbb.addBool(9, object.isPriority);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final remoteIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final contentParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final summaryParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final imageUrlParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 14);
          final sourceNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 16, '');
          final publishDateParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0));
          final isReadParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 20, false);
          final isPriorityParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 22, false);
          final object = NewsItem(
              id: idParam,
              remoteId: remoteIdParam,
              title: titleParam,
              content: contentParam,
              summary: summaryParam,
              imageUrl: imageUrlParam,
              sourceName: sourceNameParam,
              publishDate: publishDateParam,
              isRead: isReadParam,
              isPriority: isPriorityParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [NewsItem] entity fields to define ObjectBox queries.
class NewsItem_ {
  /// see [NewsItem.id]
  static final id =
      obx.QueryIntegerProperty<NewsItem>(_entities[0].properties[0]);

  /// see [NewsItem.remoteId]
  static final remoteId =
      obx.QueryStringProperty<NewsItem>(_entities[0].properties[1]);

  /// see [NewsItem.title]
  static final title =
      obx.QueryStringProperty<NewsItem>(_entities[0].properties[2]);

  /// see [NewsItem.content]
  static final content =
      obx.QueryStringProperty<NewsItem>(_entities[0].properties[3]);

  /// see [NewsItem.summary]
  static final summary =
      obx.QueryStringProperty<NewsItem>(_entities[0].properties[4]);

  /// see [NewsItem.imageUrl]
  static final imageUrl =
      obx.QueryStringProperty<NewsItem>(_entities[0].properties[5]);

  /// see [NewsItem.sourceName]
  static final sourceName =
      obx.QueryStringProperty<NewsItem>(_entities[0].properties[6]);

  /// see [NewsItem.publishDate]
  static final publishDate =
      obx.QueryDateProperty<NewsItem>(_entities[0].properties[7]);

  /// see [NewsItem.isRead]
  static final isRead =
      obx.QueryBooleanProperty<NewsItem>(_entities[0].properties[8]);

  /// see [NewsItem.isPriority]
  static final isPriority =
      obx.QueryBooleanProperty<NewsItem>(_entities[0].properties[9]);
}
